name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  marquee: ^2.2.3
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.5.0
  intl: ^0.20.2
  http: ^1.4.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  image_picker: ^1.0.4
  dio: ^5.8.0
  dartz: ^0.10.1
  jwt_decoder: ^2.0.1
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  local_auth: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Poppins/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
